### ISSUE TITLE
pk pkg fetch: add package fetching support

### ISSUE THREAD

**Issue by radhermit** [pkgcraft/pkgcraft#111]
This should be parallelized and support dep/path restrictions.

**Comment by Flowdalic** [comment]
Tex Live packaging would also benefit from it. I would need something like

`pk pkg fetch /my/dist/dir dev-texlilve/*::tex-overlay`

which populates `my/dist/dir` with all distfiles from all matching packages either by obtaining the distfile from portage's distdir, or, if it is not there, by downloading it directly from `SRC_URI` (and not involving `GENTOO_MIRRORS`).

**Comment by radhermit** [comment]
> Tex Live packaging would also benefit from it. I would need something like
> 
> `pk pkg fetch /my/dist/dir dev-texlilve/*::tex-overlay`
> 
> which populates `/my/dist/dir` with all distfiles from all matching packages either by obtaining the distfile from portage's distdir (reflinked, with potential hardlink fallback, if possible), or, if it is not there, by downloading it directly from `SRC_URI` (and not involving `GENTOO_MIRRORS`).

This should now be possible with the initial implementation now in git via something like `pk pkg fetch -d /my/dist/dir dev-texlive/*::tex-overlay`. Currently it defaults to 3 concurrent downloads, but it can be set to whatever you want bounded by the system's core count (so as not to go crazy if running across the entire tree).

Progress output currently uses multiple progress bars based on concurrency and probably still needs tweaking for better output. For example, it could be nice to show completion per pkg as well, instead of just completion per URL.
