### ISSUE TITLE
add basic logging support

### ISSUE THREAD

**Issue by radhermit** [pkgcraft/pkgcraft#25]
Mostly for initial debugging support as the protocol is fleshed out.

**Comment by lu-zero** [comment]
do you have a preference between [fern](crates.io/crates/fern) and [tracing](https://crates.io/crates/tracing)?

**Comment by radhermit** [comment]
Being unfamiliar with either of those I'm not sure. Glancing at their summaries, perhaps tracing might fit the structure better in terms of being designed for async systems in mind.

**Comment by radhermit** [comment]
Logging support now uses tracing starting with https://github.com/pkgcraft/pkgcraft/commit/c951c794de4ae9a2f0b02d0f4d6fea4b252aad77.
