### ISSUE TITLE
use the `cc` and `inline-c` crates to replace meson usage for tests

### ISSUE THREAD

**Issue by radhermit** [pkgcraft/pkgcraft#75]
See https://wasmer.io/posts/novel-way-to-develop--test-and-document-c-libraries-from-rust for some examples of how to use `inline-c`.

**Comment by lu-zero** [comment]
I forgot to tell you about a couple of shortcomings when you want parametrized tests and inline-c, I opened https://github.com/Hywan/inline-c-rs/issues/19 to address it upstream.

**Comment by radhermit** [comment]
Closing this because upstream hasn't made any movement and since the main purpose of the C library is to support language bindings, technically the C library is highly tested (in better languages to write tests in) by bindings that extensively cover it (currently python).

Also, the meson tests are being dropped for now as well because I see them as semi-pointless due to all the bindings tests that exercise the interface.

What I could see inline-c being used for in the future is doctests once `cargo nextest` supports running them as `cargo test` probably would break in various places due to running via threads instead of processes similar to pkgcraft.
