### ISSUE TITLE
add portage vdb repo support

### ISSUE THREAD

**Issue by radhermit** [pkgcraft/pkgcraft#83]
It would be handy to be able to support vdb repos for people writing scripts or tools for portage-centric systems. This probably would entail only read-only support as pkgcraft isn't planning to be portage-compatible (beyond PMS) like pkgcore.

**Comment by vincentdephily** [comment]
If you're going in that direction, maybe `mtimedb` as well ? I'm reading it to [get portage's resume list](https://github.com/vincentdephily/emlop/blob/51919ec08a2c430575d1e898040f159cace34691/src/parse/current.rs#L67).

**Comment by radhermit** [comment]
> If you're going in that direction, maybe `mtimedb` as well ? I'm reading it to [get portage's resume list](https://github.com/vincentdephily/emlop/blob/51919ec08a2c430575d1e898040f159cace34691/src/parse/current.rs#L67).

I'm not sure how far down the rabbit hole I want to go supporting two systems as pkgcraft-related tools (if they get that far) won't use portage-centric files. Currently I see the current repos.conf support, potential vdb support, and hypothetically a tool to translate portage configs to pkgcraft equivalents as the only exceptions to that.

Beyond that it feels like most other support should be in a separate, portage-related crate because unfortunately I have little interest in developing or maintaining that at the moment.

**Comment by vincentdephily** [comment]
Fair enough, you need to keep scope creep in check, and mtimedb is simple enough that I probably wouldn't pull in pkgcraft for that.

Putting all the portage-specific code in its own crate sounds like a good idea, as it might attract contributions from the portage community. Emlop is portage-centric for now, and there's probably things that would deserve collaboration with an external crate (for example getting portage's per-ebuild tmpdir). Long term I'd love to make emlop work with pkgcraft and other PMs.

**Comment by radhermit** [comment]
Revisiting this idea, I don't think it's worth the time to implement and maintain support for the current vdb format that splits up package attributes into 30+ separate files per package especially since pkgcraft-based tools won't store this information in the same fashion.

I'll reconsider reopening this if some of the format changes proposed on the gentoo-dev mailing list ever occur.
